### ISSUE TITLE
Default port 80 conflicts with other services

### ISSUE THREAD

**Issue by ghn** [bitnami/bitnami-docker-discourse#114]
**Description**

Discourse containers goes on port 80 by default and this value is even hard coded. It conflicts with other services, such as Traefik.

This is the problem: https://github.com/bitnami/bitnami-docker-discourse/blob/master/docker-compose.yml#L18

My setup:
* I added this git repo as submodule to my project
* I override and add custom stuff with another docker-compose.yml file
* I don't want to edit the submodule myself

Benefit: I can easily upgrade this repo and have all the update (git pull, restart docker-compose, done!)

**Steps to reproduce the issue:**

Normal setup as described in the readme file.

**Describe the results you received:**

Error because port 80 is already in use by another service

**Describe the results you expected:**

I would expect to have this port easily overriden (value in .env file for example). And default should be something else.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

all versions

Docker on mac/linux. Actually this isn't relevant.

What do you think?

**Comment by marcosbc** [comment]
Hi @ghn, you can always remove the lines below from your docker-compose.yml:

```
    ports:
      - '80:3000'
```

However, that way Discourse wouldn't be accessible remotely, only in your local computer (supposing you have access to your local Docker network).

Note that Discourse **requires** being run on port 80. If you change that to 81 or any other values, icons will not be shown.

This was discussed in the Discourse community in a [post](https://meta.discourse.org/t/no-icons-because-svg-sprite-file-not-loading/103326), which includes the official response. You can also find the related issue here (where we removed support for specifying another port value): https://github.com/bitnami/bitnami-docker-discourse/issues/73.

**Comment by marcosbc** [comment]
Since there's little we can do to fix this (unfortunately), I'm closing this issue.
