### ISSUE TITLE
How to install plugins when running in Kubernetes?

### ISSUE THREAD

**Issue by prbsparx** [bitnami/bitnami-docker-discourse#119]
I've create kubernetes manifests to run the bitnami discourse image and it works well without any plug-ins.

I'm trying to figure out a portable way (meaning no human intervention needed) to install plug-ins in a repeatable manner.

Any thoughts on how to enable this?

I tried creating an initContainer using Kubernetes `git-sync` docker image that clones discourse-ldap-auth into `/bitnami/discourse/plugins/discourse-ldap-auth` but the plug-in didn't show up in discourse after the pod started.

**Comment by juan131** [comment]
Hi @prbsparx 

I guess your **initContainer** is populating the data directory `/bitnami/discourse/` before Discourse is initialized. Therefore, Discourse might be overwriting whatever content is there during the 1st boot. Could you please share the Discourse container's logs? Just to confirm this theory.

 
Probably you can use a **"sidecar"** container (instead of using an **initContainer**) that check whether Discourse was initialized (you can easily check this since a "flag" is created at `/bitnami/discourse/.initialized`) and, then, clone the plugin in the corresponding directory.

**Comment by pallavipawar521** [comment]
Trying the above mentioned solution gives error as "ERROR com.bitnami.discourse is not fully installed. You cannot execute commands"

**Comment by prbsparx** [comment]
@pallavipawar521 - we ended up just running the commands to install a plug-in each time we stand up a new discourse instance. Luckily they persist once the persistentVolume exists.
@juan131 - it would be great to pass a ENV variable to the bitnami discourse image with the list of git repos we want installed. I believe the standard discourse docker image does this.

**Comment by juan131** [comment]
Hi @prbsparx 

Thanks so much for the feedback. 

Could you please open a different issue requesting this feature? Thanks in advance
