### ISSUE TITLE
Discourse fails in k8s with Error executing 'postInstallation': Files to substitute resolved to an empty list

### ISSUE THREAD

**Issue by nzoueidi** [bitnami/bitnami-docker-discourse#126]
**Description**

I am trying to deploy Discourse into my k8s cluster. I am using the latest version, however I am having the following error 
`Error executing 'postInstallation': Files to substitute resolved to an empty list`

**Steps to reproduce the issue:**

1. Deploy discourse docker image as a kubernetes object (Deployment)
2. When the pod is up, it will crash and restart after `Configuring the Discourse database files..`

**Describe the results you received:**

Discourse deployment fails with the following error

```
nami    INFO  Initializing discourse
discour INFO  Patching Discourse...
handler WARN  Using /opt/bitnami/discourse as working directory
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at x.x.x.x:5432
postgre INFO  PostgreSQL server listening and working at x.x.x.x:5432
discour INFO  Preparing Discourse environment...
discour INFO  Configuring the Discourse database files...
Error executing 'postInstallation': Files to substitute resolved to an empty list
```

**Describe the results you expected:**

I am expecting to have Discourse up and running without any errors.

**Version**

- Discourse image: latest
- Output of `docker version`: 18.09.7
- Kubernets version: 1.14

**Comment by alemorcuq** [comment]
Hi, @nzoueidi.

Could you share with us the manifests you are using to deploy Discourse?

**Comment by nzoueidi** [comment]
Hey @alemorcuq, actually I fixed the problem. The issue was that there was some files that can't be displayed (conf and logs). They had many symbolic links. What I did is rebuilding my image with a clean docker image of discourse solved the issue. 
I can see that this has been happening already to other users (ref #90). However this happened in k8s cluster that exist in Azure and the volume(s) we used are fileshare. Is there any reason why this is happening?

**Comment by marcosbc** [comment]
Hi @nzoueidi, sorry for not getting back to you earlier, I assume we lost the notification. That happens when there was an issue running the first initialization of Discourse. Once this completes you should not worry on this happening again, meaning there won't be any case where you lose any data.

In #90 the issue was happening because the user was specifying the wrong mount point for PostgreSQL, `/bitnami` instead of `/bitnami/postgresql`, so the data was not actually being persisted and thus Cassandra failing because it had been initialized, but the database was empty.

In any case, I'm glad you were able to solve your issue. I'll close this issue but feel free to add any coment if you find any related problems.
