### ISSUE TITLE
Add ability to add plug-ins in scalable way

### ISSUE THREAD

**Issue by pboushy** [bitnami/bitnami-docker-discourse#127]
Right now to install plug-ins, you have to: 

1. have a persistent volume, 
2. docker exec or ssh into the container, 
3. pull down the files, 
4. run `RAILS_ENV=production bundle exec rake assets:precompile`

This isn't scalable or able to be version controlled.

It would be ideal to be able to somehow pass a list of git repos to the docker image, and if those plugins aren't installed, the container installs them during startup. (Or updates if needed)

If this isn't feasible, a best known method being posted in the instructions would be helpful as well.

**Comment by javsalgar** [comment]
In some of our containers, such as WordPress, we introduced the ability to execute post-init scripts. I think that these could cover your use case. 

https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh

Would that work for your case?

**Comment by cburmeister** [comment]
This solution works for me:
```dockerfile
FROM bitnami/discourse:2

RUN cd /opt/bitnami/discourse/plugins && \
    git clone https://github.com/discourse/discourse-openid-connect
```

**Comment by prbsparx** [comment]
@javsalgar - so mount whatever post-init scripts into `/docker-entrypoint-init.d/` and it'll run them?
That could probably work, though I'm liking cburmeister's method.

It would allow me to fix the helvetica issue I've been seeing in 2.1.8...

@cburmeister do you know if I could modify the phusion passenger stuff that actual handles the incoming http/s requests?
I need to make Discourse see the actual clients' IPs by adding X-Forwarder-For...

**Comment by javsalgar** [comment]
Hi,

I also like the idea of creating a forked container that contains the plugins that you are interested in. In any case, when we implemented the init script feature we will let you know as well

**Comment by cburmeister** [comment]
@prbsparx I'm unfamiliar with the phusion passenger sorry!

**Comment by cdupont** [comment]
Hi @cburmeister, I tried your method and personalized the image.
However, in the Discourse settings->Plugins, it still says "You don't have any plugins installed."

**Comment by javsalgar** [comment]
Do they appear in the container when entering inside?

**Comment by cdupont** [comment]
OK, I understood the problem... I have a mounted volume at /opt/bitnami/ so updating the image has no effect.
However I just need to go on the host and git clone on the host volume mount point:
```
cd data/discourse/discourse//plugins 
git clone https://github.com/discourse/discourse-openid-connect
```

**Comment by javsalgar** [comment]
Maybe you can create like an init container that does all the cloning you require

**Comment by prbsparx** [comment]
I tried creating an initial container initially and it didn't work. I'll double check my notes on what about it didn't work... but that's why I opened this request.

**Comment by javsalgar** [comment]
Please do not hesitate to share the docker-compose that you used so we can reproduce

**Comment by ArcticSnowman** [comment]
Seem that the contents of `/opt/bitnami/discourse/plugins` is over written by the contents of `/bitnami/discourse/plugins` on start up if the later exists.

So once a persistent volume is used for `/bitnami` you can not add/remove plugins by creating a local version of the Discourse image.

I did find that the instructions here work:
https://docs.bitnami.com/aws/apps/discourse/configuration/install-plugins/
Just the directory path is `/opt/bitnami/discourse` rather than `/opt/bitnami/apps/discourse/htdocs`

**Comment by ArcticSnowman** [comment]
This could lead to the core plugins never getting updated when the core bitnami discourse image gets an updated version of discourse.

**Comment by javsalgar** [comment]
Hi,

Please note that https://docs.bitnami.com/aws/apps/discourse/configuration/install-plugins/ is for our Single VMs, which use a technology different from our containers. About the issue of plugins not getting updated, I find it non-trivial. Maybe, before restoring, we could update the plugins in the volume by copying the contents of `/opt/bitnami/discourse/plugins` to `/bitnami/discourse/plugins`, but what if users are working on modifications of these plugins? Maybe this could be configured using an ENV var, thoughts on that?

**Comment by ArcticSnowman** [comment]
Yeah I'm not sure what would be a good solution here, for example

1.  You could have a env var like `BITNAMI_DISCOURSE_UPGRADE_PLUGINS` that  would cause the start up scripts to copy `/opt/bitnami/discourse/plugins` over `/bitnami/discourse/plugins` before it's linked back.
2. if a user is actively working on a plugin they could touch a file like `.no_upgrade` in the root and the start up would not copy it over when the env var is set?
3. Make the envvar `BITNAMI_DISCOURSE_SAFE_UPGRADE_PLUGINS` be a list of plugins that are safe to upgrade?

**Comment by javsalgar** [comment]
In my opinion, the env var would be something not enabled by default so we maintain the same logic in the container. I think the name could be something like `DISCOURSE_UPGRADE_DEFAULT_PLUGINS`. For the time being it could be set to `no`, and maybe in the future, if there's an actual use case of users wanting to have a list, we could revisit it. Thoughts?

**Comment by marcosbc** [comment]
Hi, FYI we just released a new container version, [2.7.0-debian-10-r4](https://github.com/bitnami/bitnami-docker-discourse#270-debian-10-r4). The initialization logic has received a major refactor, and its scripts are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/).

Unfortunately we have not made progress for this specific issue, but now it will be a lot easier if you want to contribute plugin installation support.

**Comment by hpoul** [comment]
@marcosbc is there more involved in installing a plugin than putting a `git clone ` into a `init.d` script? 🤔️ probably handling updates to already installed plugins? Are those run before `libdiscourse.sh` / `discourse_rake_execute assets:precompile`?

**Comment by marcosbc** [comment]
Hi @hpoul, the `init.d` scripts are executed after `discourse_initialize` but before it is started. Therefore, they are executed after the `assets:precompile` script (so it would need to be executed again).

Note that scripts in `init.d` are executed only once, so it would only affect the initialization time of the first deployment. Afterwards, the default initialization sequence will be executed (with no init scripts being executed).

I have checked the [plugin installation method](https://meta.discourse.org/t/install-plugins-in-discourse/19157) using the [official Discourse Docker image](https://github.com/discourse/discourse_docker), and it seems to me like they are recommending following a more-or-less similar approach, by installing plugins in a post-installation step.

**Comment by hpoul** [comment]
@marcosbc thanks for the detailed answer. What exactly do you mean with executed only once on the first deployment? The first deployment of the image in a new container, or the first deployment for a given discourse instance (ie. only when the data directory does not yet exist)?

Because I would like to install plugins for existing discourse instances, it would mean that `init.d` would not be the right approach 🤔️

**Comment by marcosbc** [comment]
What I mean is that the plugins would only be installed automatically the first time you are deploying Discourse.

If you wanted to install plugins for an existing Discourse instance, then I'd recommend running the commands manually instead, since it's easier that way. Once you restart/recreate the container, the plugins will be persisted so you won't need to execute any other commands.

Note that init scripts are executed once, but if they were not executed in the first deployment (i.e. because of not being mounted) they should be executed at the next deployment after they are mounted to the proper folder. So for your specific use case, it should be valid as long as you did not have any other init scripts installed before.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
