### ISSUE TITLE
Info around Discourse Dockerfile, images and helm-chart

### ISSUE THREAD

**Issue by LucaPrete** [bitnami/bitnami-docker-discourse#132]
Hello guys,

Thank you for providing these awesome images. I just have few questions. Hope I'm posting in the right place, otherwise, feel free to redirect me somewhere else.

* Is it an stand-alone effort from bitnami or something in collaboration with the discourse community? FYI I've just followed up to an interesting thread over there...https://meta.discourse.org/t/community-supported-official-docker-image/83768/24?u=luca_prete

* I don't see any Dockerfile, anywhere, at least for the Discourse container. Is there one anywhere? Besides knowing what base image is used, what options have been set in the container, the biggest challenge is to understand what exact Discourse version is used in the image

* Most of all! We'd love to see a stable helm-chart. Do you think we'll get one soon? This would be tremendously helpful.

**Comment by carrodher** [comment]
> Hello guys,
> 
> Thank you for providing these awesome images. I just have few questions. Hope I'm posting in the right place, otherwise, feel free to redirect me somewhere else.

Hi, yes this is the right place, thanks for your kind words, we are happy to help.
 
> * Is it a stand-alone effort from bitnami or something in collaboration with the discourse community? FYI I've just followed up to an interesting thread over there...https://meta.discourse.org/t/community-supported-official-docker-image/83768/24?u=luca_prete

This container is "a stand-alone effort from Bitnami" plus community contributions, we are happy to receive feedback from users through GitHub Issues or PRs. But there is not a collaboration with the Discourse maintainers.

> * I don't see any Dockerfile, anywhere, at least for the Discourse container. Is there one anywhere? Besides knowing what base image is used, what options have been set in the container, the biggest challenge is to understand what exact Discourse version is used in the image

You can find the _Dockerfile_, _docker-compose.yaml_ and the required files/directories to build the image in the [2/debian-10](https://github.com/bitnami/bitnami-docker-discourse/tree/master/2/debian-10) folder. Please note that this folder can change when a new version or distro appears, but all the Bitnami images have the _Dockerfile_ and related files in a path like `BRANCH/DISTRO`.

> * Most of all! We'd love to see a stable helm-chart. Do you think we'll get one soon? This would be tremendously helpful.

Thanks for the suggestions, in the short term we are focused on the infrastructure chart catalog (like databases, servers, etc) instead of web-applications, but it is something we have in our TO-DO list and we will add more web-applications when possible and according to other priorities. In that case, Discourse will be one of the options.

**Comment by LucaPrete** [comment]
Thank you Carlos!

I'll maybe try to come up soon with a helm-chart. Might be possibly a place
for you guys to start, who knows...I'll let you know as soon as I can.

-Luca

Il giorno lun 2 mar 2020 alle ore 19:23 Carlos Rodríguez Hernández <
notifications@github.com> ha scritto:

**Comment by carrodher** [comment]
Thank you @LucaPrete, that is awesome, we will be happy to review it.
As you may know, the stable chart repository is going to disappear soon so Bitnami is working to move the charts contributed to `stable` to the [Bitnami chart repository](https://github.com/bitnami/charts). You can see the full context in this issue: https://github.com/helm/charts/issues/20969

If you have something more or less ready you can create a PR in the above repo, we will be happy to review and help with that. We need to do some changes in our internal pipeline to update the container images inside the chart, but that is our business 😄

**Comment by paulczar** [comment]
Hey @LucaPrete I've actually just started building a Helm chart for [bitnami] discourse myself.  It's not comprehensive, but it does work!

https://github.com/paulczar/community-in-a-box/tree/master/charts/discourse

**Comment by carrodher** [comment]
Hi,

Thank you both for your proposal, we are happy to add new charts to this repository and incorporate users/community charts here because of the `stable` repository deprecation.

There are only three major requirements:
- The chart should use Bitnami based container images
- Follow the same structure/patterns that the rest of the Bitnami charts
- Use an [OSI approved](https://opensource.org/licenses) license for all the software

We have a guide about [Best Practices for Creating Production-Ready Helm charts](https://docs.bitnami.com/tutorials/production-ready-charts/) but apart from that, I recommend you to use one of the existing charts as an example.

In the same way, we recently migrated our charts from `stable` to this repository. As part of the 2nd-day operations, we are going to create some contributions guideline for this repository, but they are still in progress due to the early stage of the migration.

In this case, the docker image is already created so only the chart needs to be implemented. Once created the chart we will take care of integrating everything into our pipeline to get the benefit of the automatic updates, push to the main registries, etc.

Again, thank you and please, don't hesitate to ping us if you want to incorporate this chart to the catalog.

**Comment by LucaPrete** [comment]
Hello guys!

Sorry for the late reply. I'm finishing with the migration of the entire
infrastructure, which uses (also) discourse.
To be quick, at the moment we've moved it to another VM and we've used the
default docker-scripted installation.

I plan to finish these activities by the end of the week, maybe
before...then I'll start building the chart and commit it as a PR to the
repo.

Paul, I don't want to overlap with your work. Do you plan to start
committing it as a base for the new chart, or should I create a new one,
starting from one of the existing ones, as suggested by Carols?

Please, let me know!

Ciao

-Luca

Il giorno lun 16 mar 2020 alle ore 09:22 Carlos Rodríguez Hernández <
notifications@github.com> ha scritto:

**Comment by paulczar** [comment]
@LucaPrete I'm happy to commit the chart I wrote to the bitnami repo ... why don't you use it from my repo and make sure it works as you need, then we can commit back to bitnami when it suits both our use cases.

**Comment by LucaPrete** [comment]
Paul, let me have a closer look at you chart.
We can do either way, but I'd prefer we both commit to the same PR (which
can initially even be a draft, so not publicly visible outside us three)
directly on the bitnami repo.

What if you start forking the Bitnami repo and you start committing to the
forked repo your code? If you then give me push access to it I can start to
push code to it as well. Then, when we're ready we can create a PR on the
official repo.

Thanks,

-Luca

Il giorno lun 16 mar 2020 alle ore 21:46 Paul Czarkowski <
notifications@github.com> ha scritto:

**Comment by carrodher** [comment]
On our side it is not a problem having the PR public, in fact I am sure more people here are happy to take a look! So feel free to do whatever you prefer. For us, we will be happy to review this chart and add things on our side to integrated everything into our automated release pipeline.

**Comment by LucaPrete** [comment]
Sounds good to me! Please, keep in mind it will be a WIP for a bit..

Paul, if you'd like please proceed with the initial commit and we'll take
it from there.

Thanks,

-Luca

Il giorno mar 17 mar 2020 alle ore 13:45 Carlos Rodríguez Hernández <
notifications@github.com> ha scritto:

**Comment by paulczar** [comment]
Okay here's the PR  https://github.com/bitnami/charts/pull/2072

@LucaPrete you can PR into my discourse branch and when I merge it should become part of this PR.  Feel free to chat me up on kubernetes slack (@paulczar) rather than waiting for me to notice in github.

**Comment by carrodher** [comment]
Thank you! 🎉  We will review the PR and do/suggest changes to adapt the chart to the Bitnami way

**Comment by LucaPrete** [comment]
Hello Carlos,

I'm working with Paul on some basic changes (from the PR: adapt the readme
following other READMEs, remove license, remove gitignore, ...).
Before moving forward with more substantial changes, I'd like to know if
you see something specifically wrong with the patch.
Please, live out readmes, .*ignore files. We should be ok with those and
changes should come in soon.

Looking forward to hearing from you so we can move forward.

Thanks,

-Luca

Il giorno mer 18 mar 2020 alle ore 08:28 Carlos Rodríguez Hernández <
notifications@github.com> ha scritto:

**Comment by LucaPrete** [comment]
One question on top of my mind. Can we avoid to support helm 2 (as now in
the chart Paul published), or should we necessarily find a way to support
both 2 and 3?

Thanks again,

-Luca

Il giorno lun 30 mar 2020 alle ore 11:26 Luca Prete <preteluca@gmail.com>
ha scritto:

**Comment by carrodher** [comment]
Hi! I just pinged more people in the team to review the chart, I've personally taken a quick look, but I want to take a closer/deeply one.

Regarding the Helm versions, we currently support both (2 & 3) because although we don't have specific usage data, taking a look at the support cases we receive via GitHub issues we are seeing cases using both versions without a difference, probably when the trend changes and/or Helm 2 is totally deprecated we will move everything to a Helm 3 approach, but in the meantime we need to support Helm 2 (for example by using `requirements.yaml`/`.lock` instead of `Chart.lock`, etc)

**Comment by LucaPrete** [comment]
Carlos, all thanks a lot! You feedback guys would be super helpful.
I don't know Paul personally, but I can tell he has quite a long experience
with go and helm, after briefly looking at his chart.
I think he did a great job. At this point it's just a matter of refactoring
things a little bit to make it compliant with the format/best-practices you
guys usually adopt.

For helm2/3, is the requirements.yaml still supported in 3? I thought both
approaches should be used in case we needed to support both...but my bad,
I've never really tried to use a requirements.yaml in one of my charts with
helm 3.

Cheers,

-Luca



Il giorno lun 30 mar 2020 alle ore 18:12 Carlos Rodríguez Hernández <
notifications@github.com> ha scritto:

**Comment by carrodher** [comment]
Hi,

I am sure this work will turn out great! 😄 

Yes, `requirements.yaml` and `requirements.lock` works in both Helm versions, so at this moment we are using this approach to maintain backward compatibility.

**Comment by LucaPrete** [comment]
Great! I'll send a patch to Paul repo for this.

-Luca

Il giorno mar 31 mar 2020 alle ore 09:59 Carlos Rodríguez Hernández <
notifications@github.com> ha scritto:

**Comment by marcosbc** [comment]
Since the Helm chart was already published, I'm going to close this issue
