### ISSUE TITLE
SQL init script not working in  post-init

### ISSUE THREAD

**Issue by kkorada** [bitnami/bitnami-docker-discourse#200]
**Description**

While running a sql file using post-init scripts, it is saying 

**Steps to reproduce the issue:**

1. mount a SQL file in /docker-entrypoint-init.d
2. make sure to delete . user_scripts_initialized file, if it is already present post-init.sh wont execute
3. re deploy the pod

**Describe the results you received:**

Getting error
```
INFO  ==> Executing /docker-entrypoint-init.d/s3-config-init.sql
/post-init.d/sql-postgresql.sh: line 21: POSTGRESQL_PASSWORD: unbound variable
```

**Describe the results you expected:**

Script should be executed

**Additional information you deem important (e.g. issue happens only occasionally):**

POSTGRESQL_PASSWORD is not injected as env var

**Version**
discourse-4.2.7

**Comment by kkorada** [comment]
If USERNAME AND PASSWORD are provided manually getting below error

```
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by carrodher** [comment]
The logic to execute SQL files is placed in this file: https://github.com/bitnami/bitnami-docker-discourse/blob/master/2/debian-10/rootfs/post-init.d/sql-postgresql.sh

The weird thing is that providing the password and the username should work. In order to reproduce the same issue on our side, can you share with us (although using fake user/pass) your changes in the Helm Chart and the custom SQL file?

**Comment by kkorada** [comment]
@carrodher , no changes are done in the chart.

SQL file

```
INSERT INTO public.site_settings (name, data_type, value, created_at, updated_at)
VALUES('s3_upload_bucket', 1, 'value-s3_upload_bucket', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) 
ON CONFLICT (name) 
DO 
   UPDATE SET value = 'value-s3_upload_bucket' , updated_at = CURRENT_TIMESTAMP;
```

**Comment by kkorada** [comment]
any update ??

**Comment by carrodher** [comment]
I was able to reproduce the issue by using docker-compose, so the issue is in the image and not in the Helm Chart. For that, I used this basic SQL file:
```sql
 \l
 \c bitnami_discourse
 SELECT * FROM categories;
```

And mounted it in the Discourse container using the _docker-compose.yml_ present in this repository:
```diff
@ docker-compose.yml:23 @ services:
      - '80:3000'
    volumes:
      - 'discourse_data:/bitnami/discourse'
+     - '/home/db-init.sql:/docker-entrypoint-init.d/db-init.sql'
    depends_on:
      - postgresql
      - redis
```

The Discourse containers fail with the following issue:
```
discourse_1   | discourse 11:42:06.42 INFO  ==> Executing /docker-entrypoint-init.d/db-init.sql
discourse_1   | /post-init.d/sql-postgresql.sh: line 21: POSTGRESQL_PASSWORD: unbound variable
bitnami-docker-discourse_discourse_1 exited with code 1
```

I just created an internal task to investigate and fix the issue, although I can't provide an ETA for it since we are a small team with different priorities so I am not sure when this task is going to be considered for development. As all the logic is open source and present in this repository, we will be happy to review any PR just in case you want to contribute in the meantime.

**Comment by kkorada** [comment]
@carrodher , its not just USERNAME and PASSWORD, even if we provide them manually from deployment as ENV still it throws a different error, as below:

```
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

```

**Comment by carrodher** [comment]
Thanks for letting us know, I just added this information to the internal task

**Comment by kkorada** [comment]
Hi, looks like psql is not getting connection to db as ip/host is not set. we can change the script as below:

```
postgresql_execute() {
    local -r sql_file="${1:?missing file}"
    if [[ -n "$DISCOURSE_DATABASE_PASSWORD" ]]; then
            export PGPASSWORD=$DISCOURSE_DATABASE_PASSWORD
    fi
    local -a psql=("psql")
    if [[ -n "${DISCOURSE_DATABASE_USER:-}" ]]; then
        psql+=("-U" "$DISCOURSE_DATABASE_USER")
    fi
    if [[ -n "$DISCOURSE_DATABASE_HOST" ]]; then
        psql+=("-h" "$DISCOURSE_DATABASE_HOST") 
    fi
    if [[ -n "$DISCOURSE_DATABASE_PORT_NUMBER" ]]; then
        psql+=("-p" "$DISCOURSE_DATABASE_PORT_NUMBER") 
    fi
    if [[ -n "$POSTGRESQL_CLIENT_CREATE_DATABASE_NAME" ]]; then
        psql+=("-d" "$POSTGRESQL_CLIENT_CREATE_DATABASE_NAME") 
    fi
    if [[ "$sql_file" == *".sql" ]]; then
        "${psql[@]}" -f "$sql_file" || failure=$?
    elif [[ "$sql_file" == *".sql.gz" ]]; then
        gunzip -c "$sql_file" | "${psql[@]}" || failure=$?
    fi
    return "$failure"
}
```

**Comment by kkorada** [comment]
let me know if this works I can create a PR

**Comment by carrodher** [comment]
Yep, sure, we need to test it but it looks like a good approach. Feel free to create the PR and also it would be nice if you can add to the description some results of the logic working on your environment.

Thank you very much, our team will be happy to review that PR!

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-discourse#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
